name: Build web version

on:
    push:
        paths:
            - 'src/**'
    workflow_dispatch:

jobs:
    run-npm-script:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: npm install

            - name: Run build script
              run: npm run build

            - name: Commit changes
              continue-on-error: true
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add ./build
                  git commit -m "build: build web lib version"

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
