name: Build and Commit

on:
    push:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install Node.JS
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - run: npm i
            - run: npm run build

            - name: Commit built files
              run: |
                  git config --global user.name 'GitHub Actions Bot'
                  git config --global user.email 'actions@github.com'
                  git add build/index.web.js
                  git commit -m "build: build index.web.js" || echo "No changes to commit"
                  git push
